### ISSUE TITLE
[Bug]: Impossible to set "keep_database_and_schema"

### ISSUE THREAD

**Issue by JesusRedGar** [liip/LiipTestFixturesBundle#254] opened 2024-01-11 13:37 UTC
### Preconditions

Version currently installed:
- 2.7.0

Symfony:
- 6.3

PHP:
8.2

### Steps to reproduce

I try to avoid the database and schema creation using the method described in the documentation: [https://github.com/liip/LiipTestFixturesBundle/blob/2.x/doc/configuration.md](https://github.com/liip/LiipTestFixturesBundle/blob/2.x/doc/configuration.md)

Setting _keep_database_and_schema: true_ does not prevent from doing so.

I am debugging the execution and in the file: **ORMDatabaseTool.php** There is the following fragment in line 72:

```php
        if (false === $this->getKeepDatabaseAndSchemaParameter()) {
            $this->createDatabaseIfNotExists();
        }

```

No matter what I set _keep_database_and_schema_ to, it always get the value false in that line.

**It might be an error because the config yaml file is not loaded.** I attached a pinture to show where is placed and its content:

![image](https://github.com/liip/LiipTestFixturesBundle/assets/124564315/51f05e7c-2702-4e72-a72c-5581e47bc9cc)

Not sure how to debufg if this is what is failing.

### Expected result

Expected keeping database and schema intact.

### Actual result

It does not keep database and schema intact.

**Comment by JesusRedGar** [comment] 2024-01-12 10:05
It solved itself... I don't know what happened. But now the configuration from the yaml file is loaded and now it works as expected.

**Comment by alexislefebvre** [comment] 2024-01-12 10:19
Do you have something like the following code in the `src/Kernel.php` file?

```php
$loader->load($confDir.'/{packages}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, 'glob');
```

This code loads the files in `config/dev/`, `config/test/`,etc.

**Comment by JesusRedGar** [comment] 2024-01-12 12:34
> ```
> $loader->load($confDir.'/{packages}/'.$this->environment.'/**/*'.self::CONFIG_EXTS, 'glob');
> ```

I dont have that line or anything similar. But all other packages had load without problems before (and their configurations in /dev /test). That is why I supposed the error was specific of this package.

**Comment by alexislefebvre** [comment] 2024-01-12 14:15
Thanks for your report, let's close this issue since it's not reproducible.

**Closed as not planned by alexislefebvre** 2024-01-12 14:15 UTC
Labels: bug
