### ISSUE TITLE
facing issue in new pimcore version 10.6 

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [liip/LiipTestFixturesBundle#236] opened 2023-08-10 06:47 UTC
### Preconditions

Im using PHP 8.1, Symfony 5.4, Pimcore 10.6.7

### Steps to reproduce

When I'm calling `WebsiteSetting::getByName('SAML_ENV');`

gets error in my dependency injection file, which is having method

```php
public function prepend(ContainerBuilder $container){
   WebsiteSetting::getByName('SAML_ENV');
}
```

please help to solve this issue

Thanks in advance

### Expected result

It should work

### Actual result

Getting error of

### **"Cannot retrieve the container from a non-booted kernel."**

this error showing in the line `WebsiteSetting::getByName('SAML_ENV');`

**Comment by alexislefebvre** [comment] 2023-08-10 09:44
How does it relate to LiipTestFixturesBundle ?

Please share the code of the test file, as a [minimal, complete and verifiable example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by Thejaswini-Rao-U** [comment] 2023-08-10 09:51
@alexislefebvre , i thought its related to symfony issues and discussions forum so i have posted here.

**Comment by alexislefebvre** [comment] 2023-08-10 09:54
You can find help about Symfony here:

- https://github.com/symfony/symfony/discussions
- https://stackoverflow.com/questions/tagged/symfony

**Comment by Thejaswini-Rao-U** [comment] 2023-08-10 09:56
Okay thanks

**Comment by alexislefebvre** [comment] 2023-08-10 10:08
I'm closing this issue since it's unrelated to the LiipTestFixturesBundle software.

**Closed as not planned by alexislefebvre** 2023-08-10 10:08 UTC
Labels: bug
