### ISSUE TITLE
SqlitePlatform::getName() is deprecated

### ISSUE THREAD

**Issue by craigh** [liip/LiipTestFixturesBundle#253] opened 2023-12-06 15:29 UTC
I get this deprecation notice when running my tests:

```
SqlitePlatform::getName() is deprecated. Identify platforms by their class. (SqlitePlatform.php:672 called by AbstractDatabaseTool.php:196, https://github.com/doctrine/dbal/issues/4749, package doctrine/dbal)
```

That's `\Liip\TestFixturesBundle\Services\DatabaseTools\AbstractDatabaseTool`

I was hoping you could help with that. thank you :-) 

Symfony 6.3.9
doctrine/doctrine-bundle 2.11.1
doctrine/orm 2.17.1
phpunit/phpunit 9.6.15
liip/functional-test-bundle 4.10.0
liip/test-fixtures-bundle 2.7.0

let me know if you need other info. thank you

**Comment by alexislefebvre** [comment] 2023-12-06 16:14
Do you have an idea about how to do this?

> Identify platforms by their class.

**Comment by craigh** [comment] 2023-12-06 16:16
not really. Someone on slack said "use `SqlitePlaform::class`" but I wouldn't know where or how.

**Comment by mbabker** [comment] 2023-12-08 14:57
Duplicate of #184 😉 

For reference though, what you probably need is something like [this method](https://github.com/symfony/symfony/blob/c4e97ebac3df1094c3a50538f122d64852beb871/src/Symfony/Component/Cache/Adapter/DoctrineDbalAdapter.php#L348-L364) in the `symfony/cache` DBAL adapter which effectively replicates the deprecated `getName()` method for known platforms.

**Comment by alexislefebvre** [comment] 2024-01-13 17:30
Thanks @mbabker, let's close it and follow this subject in the other issue:

- #184

**Closed as completed by alexislefebvre** 2024-01-13 17:30 UTC
Labels: enhancement
